apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-time-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-time-app
  template:
    metadata:
      labels:
        app: golang-time-app
    spec:
      containers:
      - name: golang-time-app
        image: 88151/golang-time-app:latest
        ports:
        - containerPort: 8080

