apiVersion: v1
kind: Service
metadata:
  name: golang-time-app-service
spec:
  selector:
    app: golang-time-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001  # Use a port like 30001
  type: NodePort

